'use strict';
const $=s=>document.querySelector(s);
const STORAGE='forest-detective-v5';
const FOURTH_STORAGE='forest-detective-v4';
const THIRD_STORAGE='forest-detective-v3';
const PREVIOUS_STORAGE='forest-detective-v2';
const LEGACY_STORAGE='forest-detective-v1';
const animals=[
 {id:'rabbit',name:'绒绒',emoji:'🐰',hat:false,bag:true,shoe:'red'},
 {id:'fox',name:'阿橙',emoji:'🦊',hat:true,bag:true,shoe:'blue'},
 {id:'bear',name:'大树',emoji:'🐻',hat:false,bag:false,shoe:'blue'},
 {id:'squirrel',name:'松松',emoji:'🐿️',hat:false,bag:true,shoe:'blue'}
];
const guests=[
 {id:'cat',name:'花花',emoji:'🐱',hat:true,bag:false,shoe:'red'},
 {id:'panda',name:'团团',emoji:'🐼',hat:false,bag:true,shoe:'red'},
 {id:'dog',name:'点点',emoji:'🐶',hat:true,bag:true,shoe:'blue'},
 {id:'koala',name:'灰灰',emoji:'🐨',hat:true,bag:true,shoe:'red'}
];
const firstChapterLessons=[
 {title:'整理观察卡',short:'观察与分类',symbol:'◈',type:'sort',question:'按鞋子的颜色，把卡片分成两组。',instruction:'先点一张卡，再点对应的收纳盒。也可以拖进去。',story:'兔子奶奶准备的胡萝卜不见了！先整理朋友们的观察卡，找线索会更容易。',clues:['只看鞋子的颜色','帽子和背包先不管'],hints:['看看小动物脚上穿的鞋子，哪些是红色的，哪些是蓝色的？','绒绒穿红鞋，其余三位穿蓝鞋。'],success:'分类完成！换一个分类标准，同一组朋友就可能分到不同的地方。'},
 {title:'缩小寻找范围',short:'根据线索排除',symbol:'⌕',type:'multi',question:'哪些朋友符合第一条线索？',instruction:'选出所有符合的朋友，再检查。',story:'小鸟看见了搬胡萝卜的朋友。它记得：这位朋友没有戴帽子。',clues:['搬箱子的朋友没有戴帽子'],hints:['先找戴帽子的朋友，把他排除。','阿橙戴帽子。剩下三位都没有戴帽子，要全部选中。'],answer:['rabbit','bear','squirrel'],success:'范围缩小了！没有戴帽子的有三位，仅凭这一条线索，还不能确定是谁。'},
 {title:'拼起三条线索',short:'多条件推理',symbol:'⊕',type:'single',question:'谁同时符合三条线索？',instruction:'三条都要符合，才能作出判断。',story:'小鸟又想起来了：那位朋友背着背包，穿着蓝鞋。把三条线索放在一起吧。',clues:['没有戴帽子','背着背包','穿着蓝鞋'],hints:['绒绒穿红鞋，可以排除；阿橙戴帽子，也不符合。','大树没有背包。再看看松松的三项特征。'],answer:['squirrel'],success:'是松松！他没有戴帽子、背着背包、穿着蓝鞋，三条线索都符合。'},
 {title:'让证据来说话',short:'区分证据与猜测',symbol:'▤',type:'evidence',question:'哪些线索能支持“是松松”？',instruction:'选出小鸟真正看到的三条线索。',story:'侦探不能只说“我猜是他”。从这些卡片里找出能支持判断的证据。',clues:['回想小鸟看到的事情','喜欢什么，不代表做过什么'],options:[['hat','♧','没有戴帽子'],['food','♡','松松喜欢吃坚果'],['bag','▣','背着背包'],['shoe','◒','穿着蓝鞋']],answer:['hat','bag','shoe'],hints:['“喜欢吃坚果”是喜好，不是小鸟看到的搬箱子线索。','选没有戴帽子、背着背包、穿着蓝鞋这三张卡。'],success:'证据齐了！喜好不能证明做过什么，亲眼看到的特征才是这次判断的依据。'},
 {title:'沿着路线去找',short:'空间与顺序',symbol:'↱',type:'map',question:'松松把箱子搬到了哪里？',instruction:'从邮局出发，按卡片移动，再点终点。',story:'松松留了一张路线卡。地图上方就是北方。顺着路线，应该就能找到他！',clues:['起点：邮局','先向右走两格','再向上走一格'],hints:['先从左下角的邮局，向右移动到右下角的小桥。','再从小桥向上走一格，就到了仓库。'],answer:['warehouse'],success:'找到仓库了！先向右两格，再向上一格，走的顺序很重要。'},
 {title:'新朋友的委托',short:'迁移小挑战',symbol:'☆',type:'transfer',question:'谁来帮松松推小车？',instruction:'换了新朋友，试试同样的推理方法。',story:'松松说：“快下雨了，我把胡萝卜搬到仓库啦！还有一位朋友来帮忙。”',clues:['戴着帽子','背着背包','穿着红鞋'],hints:['花花没有背包，团团没有戴帽子。','点点穿蓝鞋。看看灰灰是不是三条都符合。'],answer:['koala'],success:'是灰灰！即使换了人物，也可以逐条检查、排除，找到同时符合条件的答案。'}
];
const CHAPTERS={carrots:{id:'carrots',number:'001',name:'胡萝卜失踪事件',subtitle:'观察线索，找到答案',title:'咦，胡萝卜<br><span>去哪儿了？</span>',description:'邮局门口的胡萝卜不见了。<br>带上你的好奇心，一起找到故事的答案。',image:'./assets/forest.png',imageAlt:'阳光下的森林邮局，门前放着胡萝卜箱子',tag:'今日委托：寻找胡萝卜的去向 🥕',audioRoot:'./assets/audio/',skills:['细心观察','逐条推理','用证据说话'],endingTitle:'好侦探，找到答案啦！',endingText:'胡萝卜没有被偷走。<br>松松和灰灰担心下雨，把它们搬进了仓库。<br>兔子奶奶说：“谢谢你们，也谢谢认真找线索的小侦探！”',endingQuestion:'你能说说，哪一条线索帮了你最大的忙吗？',lessons:firstChapterLessons},train:window.TRAIN_CHAPTER,mail:window.MAIL_CHAPTER,picnic:window.PICNIC_CHAPTER,stage:window.STAGE_CHAPTER};
const fresh=ForestProgress.fresh;
const validState=v=>Boolean(ForestProgress.normalize(v));
let state=fresh(),storageOk=true;
function readSaved(key){try{return ForestProgress.normalize(JSON.parse(localStorage.getItem(key)));}catch{return null;}}
state=readSaved(STORAGE)||readSaved(FOURTH_STORAGE)||readSaved(THIRD_STORAGE)||readSaved(PREVIOUS_STORAGE)||readSaved(LEGACY_STORAGE)||fresh();
let chapterId=state.activeChapter,lessons=CHAPTERS[chapterId].lessons;
const currentChapter=()=>CHAPTERS[chapterId];
const progress=()=>state.chapters[chapterId];
function selectChapter(id){if(!CHAPTERS[id])return;stopAudio();chapterId=id;state.activeChapter=id;lessons=CHAPTERS[id].lessons;save();home();}
let screen='home',step=0,selected=new Set(),placements={},solved=false,hintLevel=0,offlineReady=false,busy=false,registration=null,audio=null,toastTimer;
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state));storageOk=true;}catch{storageOk=false;toast('进度暂时无法保存，请在家长手册中导出备份。');}connection();}
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4200);}
function connection(){$('#connection').textContent=!storageOk?'进度仅在本次有效':offlineReady?'五章已下载 · 可离线':navigator.onLine?'本地进度已开启':'当前离线';}
function soundUI(){const button=$('#sound');button.innerHTML=`<span aria-hidden="true">${state.sound?'🔊':'🔇'}</span><span>${state.sound?'声音开':'声音关'}</span>`;button.setAttribute('aria-label',state.sound?'声音已开启，点击关闭声音':'声音已关闭，点击开启声音');button.setAttribute('title',state.sound?'点击关闭声音':'点击开启声音');button.setAttribute('aria-pressed',String(state.sound));}
function stopAudio(){if(audio){audio.pause();audio=null;}}
function speak(file,{automatic=false}={}){stopAudio();if(!state.sound){if(!automatic)toast('声音已关闭，点右上角的“声音关”即可开启。');return;}if(chapterId==='train'){if(/^s\d+$/.test(file))file='success';if(/^w\d+$/.test(file))file='retry';}if(currentChapter().audioReady===false){if(!automatic&&file.startsWith('q'))toast('这一章的千问配音正在制作中，可以先看图试玩。');return;}audio=new Audio(`${currentChapter().audioRoot}${file}-natural.${currentChapter().audioExtension||'mp3'}`);const playing=audio;playing.play().catch(e=>{if(audio!==playing||e.name==='AbortError')return;if(e.name==='NotAllowedError')toast('点一下“听一听”，就能播放这段声音。');else toast('配音暂时无法播放，请先下载整课。文字题目仍可使用。');});}
function chime(){if(!state.sound)return;try{const Context=window.AudioContext||window.webkitAudioContext;const c=new Context();[523,659,784].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=f;g.gain.setValueAtTime(.07,c.currentTime+i*.12);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+i*.12+.3);o.start(c.currentTime+i*.12);o.stop(c.currentTime+i*.12+.3);});setTimeout(()=>c.close(),1000);}catch{}}
function home(){
 screen='home';cancelPicnicDrag();stopAudio();document.body.dataset.story=chapterId;const c=currentChapter(),p=progress();
 $('#main').innerHTML=`<nav class="story-tabs" aria-label="选择章节">${Object.values(CHAPTERS).map(ch=>`<button class="story-tab" data-chapter="${ch.id}" aria-pressed="${ch.id===chapterId}"><span>${ch.number.slice(1)}</span><span><strong>${ch.name}</strong><small>${ch.subtitle}</small></span><span class="story-progress">${state.chapters[ch.id].completed} / ${ch.lessons.length}</span></button>`).join('')}</nav><section class="hero"><div class="hero-copy"><div class="eyebrow">森林档案 / NO. ${c.number}</div><h1>${c.title}</h1><p>${c.description}</p><button class="primary" id="start">${p.completed===lessons.length?'再探一次':p.completed?'继续探险':'出发，去找线索'} <span>↗</span></button><div class="hero-meta"><span>${lessons.length} 个探索任务</span><span>约 10 分钟</span><span>${c.audioReady===false?'配音制作中 · 看图试玩':'可听题'}</span></div></div><div class="hero-art" role="img" aria-label="${c.imageAlt}" style="background-image:url('${c.image}')"><div class="case-tag">${c.tag}</div></div></section><section class="home-bottom"><div><div class="section-heading"><h2>你的侦探路线</h2><span>${p.completed} / ${lessons.length} 已完成</span></div><div class="chapter-list">${lessons.map((l,i)=>`<button class="chapter ${i===p.completed?'current':''}" data-step="${i}" ${i>p.completed?'disabled':''}><span class="chapter-number">0${i+1}</span><span class="chapter-symbol">${i<p.completed?'✓':l.symbol}</span><strong>${l.title}</strong><small>${i>p.completed?'完成上一站后开启':l.short}</small></button>`).join('')}</div></div><aside class="offline-card"><h3>把五章探险装进口袋 ↧</h3><p>${Object.values(CHAPTERS).some(ch=>ch.audioReady===false)?'本地试玩：新章节配音尚未全部加入。':'一次下载五章的图片、语音和任务。'}离线也能继续探险，各章进度分别保存。</p><button class="secondary" id="home-download">${offlineReady?'✓ 五章已下载':'下载五章 · 离线玩'}</button><p id="home-download-status" role="status">${offlineReady?'准备好了！可以断网重开试一试。':'学习进度保存在这台设备上。'}</p></aside></section>`;
 $('#start').onclick=()=>start(p.completed===lessons.length?0:p.completed);
 document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>start(Number(b.dataset.step)));
 document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>selectChapter(b.dataset.chapter));
 $('#home-download').onclick=download;connection();updateButton();
}
function start(i){resetMail();step=i;screen='lesson';selected=new Set();placements={};resetPicnic(lessons[i]);resetStage(lessons[i]);solved=false;hintLevel=0;stopAudio();renderLesson();window.scrollTo({top:0,behavior:'instant'});speak(`q${i}`,{automatic:true});}
function animalCard(a){return `<button class="animal ${selected.has(a.id)?'selected':''}" data-choice="${a.id}" aria-pressed="${selected.has(a.id)}"><img class="character" src="./assets/${a.id}.png" alt="${a.name}，${a.hat?'戴帽子':'没戴帽子'}，${a.bag?'有背包':'没背包'}，穿${a.shoe==='blue'?'蓝':'红'}鞋"><strong>${a.name}</strong></button>`;}
const mapCells=[['tree','🌳','大树'],['pond','💧','池塘'],['windmill','🌼','花园'],['house','🏡','小屋'],['well','🪣','水井'],['warehouse','📦','仓库'],['post','✉️','邮局 · 起点'],['grass','🌿','草地'],['bridge','🌉','小桥']];
function token(a){return `<button class="token ${selected.has(a.id)?'selected':''}" data-token="${a.id}" aria-pressed="${selected.has(a.id)}"><img class="token-character" src="./assets/${a.id}.png" alt="${a.name}穿着${a.shoe==='red'?'红':'蓝'}鞋"><strong>${a.name}</strong></button>`;}
function boardHTML(){if(chapterId==='stage')return stageBoard();if(chapterId==='picnic')return picnicBoard();if(chapterId==='mail')return mailBoard();if(chapterId==='train')return trainBoard();const l=lessons[step];if(l.type==='sort')return `<div class="sort-tokens">${animals.filter(a=>!placements[a.id]).map(token).join('')}${Object.keys(placements).length===4?'<p>四张卡都放好了，来检查一下吧。</p>':''}</div><div class="bins">${['red','blue'].map(color=>`<div class="bin" data-bin="${color}" role="button" tabindex="0" aria-label="${color==='red'?'红鞋':'蓝鞋'}收纳盒"><h3>${color==='red'?'🔴 穿红鞋的朋友':'🔵 穿蓝鞋的朋友'}</h3>${animals.filter(a=>placements[a.id]===color).map(token).join('')}</div>`).join('')}</div>`;if(l.type==='evidence')return `<div class="evidence-grid">${l.options.map(([id,icon,text])=>`<button class="evidence ${selected.has(id)?'selected':''}" data-choice="${id}" aria-pressed="${selected.has(id)}"><span aria-hidden="true">${icon}</span>${text}</button>`).join('')}</div>`;if(l.type==='map')return `<div class="map-wrap"><div class="map">${mapCells.map(([id,emoji,name])=>`<button class="map-cell ${id==='post'?'start':''} ${selected.has(id)?'selected':''}" data-choice="${id}" aria-pressed="${selected.has(id)}"><span aria-hidden="true">${emoji}</span>${name}</button>`).join('')}</div><div class="directions"><strong>北 ↑</strong>从邮局出发<br>① 右 → 右 →<br>② 上 ↑<br><small>每次走一个格子</small></div></div>`;return `<div class="suspects">${(l.type==='transfer'?guests:animals).map(animalCard).join('')}</div>`;}
function renderLesson(){const l=lessons[step];$('#main').innerHTML=`<div class="lesson-head"><button class="back" id="back">← 返回营地</button><div class="progress-wrap"><div class="progress-label"><span>森林档案 ${currentChapter().number} · ${currentChapter().name}</span><span>探索 ${step+1} / ${lessons.length}</span></div><div class="progress" role="progressbar" aria-valuemin="0" aria-valuemax="${lessons.length}" aria-valuenow="${step}"><span style="width:${step/lessons.length*100}%"></span></div></div></div><section class="lesson ${chapterId==='carrots'?'':chapterId}"><aside class="notebook"><div class="eyebrow">我的侦探手册</div><h2>0${step+1}<br>${l.title}</h2><p>${l.story}</p><div class="clues">${l.clues.map((c,i)=>`<div class="clue"><small>线索 ${String(i+1).padStart(2,'0')}</small>${c}</div>`).join('')}</div><div class="notebook-foot">不用着急，线索一直在这里。</div></aside><div class="play-area"><div class="play-heading"><div><h2>${l.question}</h2><p>${l.instruction}</p></div><button class="listen" id="listen">♫ 听一听</button></div><div class="board" id="board">${boardHTML()}</div><div class="feedback" id="feedback" role="status" hidden></div><div class="play-controls"><button class="hint" id="hint">☼ 给我一点提示</button><button class="primary" id="check" disabled>检查我的发现 ✓</button></div></div></section>`;$('#back').onclick=home;$('#listen').onclick=()=>speak(`q${step}`);$('#hint').onclick=hint;$('#check').onclick=check;bindBoard();}
function bindBoard(){if(chapterId==='stage'){bindStageBoard();return;}if(chapterId==='picnic'){bindPicnicBoard();return;}if(chapterId==='mail'){bindMailBoard();return;}if(chapterId==='train'){bindTrainBoard();return;}document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{if(solved)return;const id=b.dataset.choice;const multi=['multi','evidence'].includes(lessons[step].type);if(multi){selected.has(id)?selected.delete(id):selected.add(id);}else{selected=new Set([id]);}refreshBoard();});document.querySelectorAll('[data-token]').forEach(b=>{b.onclick=e=>{e.stopPropagation();if(solved)return;selected=new Set([b.dataset.token]);refreshBoard();};b.onpointerdown=e=>{if(solved)return;const id=b.dataset.token;const x=e.clientX,y=e.clientY;const finish=ev=>{document.removeEventListener('pointerup',finish);if(Math.hypot(ev.clientX-x,ev.clientY-y)<12)return;const target=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('[data-bin]');if(target){selected=new Set([id]);place(target.dataset.bin);}};document.addEventListener('pointerup',finish,{once:true});b.onpointercancel=()=>document.removeEventListener('pointerup',finish);};});document.querySelectorAll('[data-bin]').forEach(b=>{b.onclick=e=>{if(e.target.closest('[data-token]'))return;place(b.dataset.bin);};b.onkeydown=e=>{if(e.target!==b)return;if(e.key==='Enter'||e.key===' '){e.preventDefault();place(b.dataset.bin);}};});$('#check').disabled=solved?false:lessons[step].type==='sort'?Object.keys(placements).length!==4:selected.size===0;}
function pictogram(id,negative=false){return `<span class="pictogram ${negative?'without':''}"><img src="./assets/clue-${id}.png" alt="${negative?'没有戴帽子':({hat:'帽子',bag:'背包',shoe:'蓝鞋',redshoe:'红鞋',food:'坚果'})[id]}"></span>`;}
function illustrateCards(){if(screen!=='lesson'||chapterId!=='carrots')return;document.querySelectorAll('.evidence').forEach(b=>{b.setAttribute('aria-label',lessons[step].options.find(o=>o[0]===b.dataset.choice)[2]);b.innerHTML=pictogram(b.dataset.choice,b.dataset.choice==='hat');});document.querySelectorAll('.clue').forEach((c,i)=>{const text=lessons[step].clues[i];let icon='';if(text.includes('没有戴帽子'))icon=pictogram('hat',true);else if(text.includes('戴着帽子'))icon=pictogram('hat');else if(text.includes('背着背包'))icon=pictogram('bag');else if(text.includes('穿着蓝鞋'))icon=pictogram('shoe');else if(text.includes('穿着红鞋'))icon=pictogram('redshoe');if(icon){c.setAttribute('aria-label',text);c.innerHTML=`<small>线索 ${String(i+1).padStart(2,'0')}</small>${icon}`;c.classList.add('picture-clue');}});}
const originalBindBoard=bindBoard;
bindBoard=function(){originalBindBoard();illustrateCards();};
function refreshBoard(){$('#board').innerHTML=boardHTML();bindBoard();}
function place(color){if(solved)return;if(!selected.size){toast('先选一张观察卡，再选收纳盒。');return;}placements[[...selected][0]]=color;selected.clear();refreshBoard();}
function feedback(text,success=false){const f=$('#feedback');f.hidden=false;f.className='feedback'+(success?' success':'');f.textContent=text;}
function hint(){if(solved)return;const l=lessons[step];feedback(l.hints[Math.min(hintLevel,1)]);speak(`h${step}-${Math.min(hintLevel,1)}`);hintLevel++;progress().hints[step]++;save();}
function check(){if(solved){if(step===lessons.length-1)ending();else start(step+1);return;}const l=lessons[step];const mailResult=chapterId==='stage'?checkStage():chapterId==='picnic'?checkPicnic():chapterId==='mail'?checkMail():null;const correct=mailResult?mailResult.ok:l.type==='slots'?Object.entries(l.slotAnswer).every(([slot,value])=>placements[slot]===value):l.type==='sort'?animals.every(a=>placements[a.id]===a.shoe):selected.size===l.answer.length&&l.answer.every(a=>selected.has(a));if(!correct){progress().mistakes[step]++;save();if(mailResult)refreshBoard();let msg=mailResult?.message||l.wrong||(l.type==='sort'?'有张卡片还没找到合适的家。逐个看鞋子的颜色，再试一次。':l.type==='multi'?'再看看：有没有漏掉符合的朋友，或者选了戴帽子的朋友？':l.type==='evidence'?'想想哪些是小鸟亲眼看到的。要把三条观察线索都选出来。':l.type==='map'?'从左下角的邮局重新出发，先向右两格，再向上一格。':'这位朋友还不能同时符合所有线索。把每一条都对照一下。');feedback(msg);speak(`w${step}`);return;}solved=true;progress().completed=Math.max(progress().completed,step+1);save();feedback(l.success,true);chime();speak(`s${step}`);if(chapterId!=='carrots')refreshBoard();$('#check').textContent=step===lessons.length-1?'揭晓故事 →':'下一站 →';$('#hint').hidden=true;document.querySelectorAll('#board button').forEach(b=>b.disabled=true);}
function ending(){
 screen='ending';stopAudio();const c=currentChapter(),chapters=Object.values(CHAPTERS),next=chapters[chapters.indexOf(c)+1];
 $('#main').innerHTML=`<section class="ending"><div class="eyebrow" style="justify-content:center">森林档案 ${c.number} · 已完成</div><div class="medal" aria-hidden="true">${chapterId==='train'?'🌟':'🏅'}</div><h1>${c.endingTitle}</h1><p>${c.endingText}</p><div class="skills">${c.skills.map(s=>`<span>✓ ${s}</span>`).join('')}</div><p>${c.endingQuestion}</p><div class="ending-actions"><button class="primary" id="home">带着徽章回营地 ↗</button><button class="secondary" id="ending-listen">♫ 听故事结局</button></div>${next?`<button class="secondary story-ending-next" id="next-chapter">下一章：${next.name} →</button>`:''}</section>`;
 $('#home').onclick=home;$('#ending-listen').onclick=()=>speak('ending');if($('#next-chapter'))$('#next-chapter').onclick=()=>selectChapter(next.id);window.scrollTo({top:0,behavior:'instant'});speak('ending',{automatic:true});
}
function parent(){const stats=Object.values(CHAPTERS).map(c=>{const p=state.chapters[c.id];return c.name+'：'+p.completed+'/'+c.lessons.length+' 个任务，尝试调整 '+p.mistakes.reduce((a,b)=>a+b,0)+' 次，提示 '+p.hints.reduce((a,b)=>a+b,0)+' 次。';});$('#parent-stats').textContent=stats.join(' ');$('#download-status').textContent=offlineReady?'五章已下载，可离线使用。':'下载五章图片、题目和全部配音后，可离线使用。';$('#parent-dialog').showModal();updateButton();}
function downloadStatus(t){for(const selector of ['#download-status','#home-download-status']){const el=$(selector);if(el)el.textContent=t;}}
async function verifyCache(){try{const name=self.FOREST_CACHE;const exists=(await caches.keys()).includes(name);if(!exists){offlineReady=false;return false;}const cache=await caches.open(name);offlineReady=(await Promise.all(self.FOREST_ASSETS.map(p=>cache.match(new URL(p,location.href).href)))).every(Boolean);return offlineReady;}catch{offlineReady=false;return false;}finally{connection();}}
function watchRegistration(reg){registration=reg;updateButton();reg.addEventListener('updatefound',()=>{const worker=reg.installing;if(worker)worker.addEventListener('statechange',()=>{if(worker.state==='installed')updateButton();});});}
function updateButton(){const b=$('#update');b.hidden=!registration?.waiting;b.disabled=screen!=='home';b.textContent=screen==='home'?'应用已下载的新版本':'更新课程（请先返回营地）';}
async function download(){if(busy)return;if(!window.isSecureContext||!('serviceWorker'in navigator)){downloadStatus('当前地址不能保存离线课程。请在 iPad 上使用 HTTPS 地址；电脑可用 localhost。');return;}busy=true;const buttons=[$('#download'),$('#home-download')].filter(Boolean);buttons.forEach(b=>b.disabled=true);downloadStatus('正在下载五章课程，请保持页面打开……');try{const reg=await navigator.serviceWorker.register('./sw.js');watchRegistration(reg);const worker=reg.installing||reg.waiting||reg.active;if(!worker)throw Error('没有可用下载任务');if(!['installed','activated'].includes(worker.state))await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{worker.removeEventListener('statechange',changed);reject(Error('下载超时'));},120000);function changed(){if(['installed','activated'].includes(worker.state)){clearTimeout(timeout);worker.removeEventListener('statechange',changed);resolve();}else if(worker.state==='redundant'){clearTimeout(timeout);worker.removeEventListener('statechange',changed);reject(Error('下载没有完成'));}}worker.addEventListener('statechange',changed);changed();});if(!await verifyCache())throw Error('资源还未完整保存');if(navigator.storage?.persist)await navigator.storage.persist().catch(()=>false);downloadStatus('✓ 五章已下载。现在可以断网，重开应用验证。');if($('#home-download'))$('#home-download').textContent='✓ 五章已下载';toast('五章下载完成，配音也已保存。');updateButton();}catch(e){await verifyCache();downloadStatus('下载未完成，请检查网络后重试。已完成的学习进度不受影响。');}finally{busy=false;buttons.forEach(b=>b.disabled=false);}}
$('#parent').onclick=parent;$('#close-parent').onclick=()=>$('#parent-dialog').close();$('#download').onclick=download;$('.brand').onclick=e=>{e.preventDefault();home();};$('#sound').onclick=()=>{state.sound=!state.sound;save();soundUI();if(!state.sound)stopAudio();};$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='森林侦探-学习进度.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#backup-status').textContent='已生成备份文件，请保存到“文件”或电脑中。';};$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>100000)throw Error();const v=JSON.parse(await file.text());if(!validState(v))throw Error();state=ForestProgress.restore(state,v);chapterId=state.activeChapter;lessons=CHAPTERS[chapterId].lessons;save();soundUI();home();$('#backup-status').textContent='进度已恢复。';$('#parent-stats').textContent=Object.values(CHAPTERS).map(c=>c.name+'：'+state.chapters[c.id].completed+'/'+c.lessons.length+' 已完成').join('；');}catch{$('#backup-status').textContent='这个文件不是有效的进度备份，原进度已保留。';}e.target.value='';};$('#update').onclick=()=>{if(screen==='home'&&registration?.waiting)registration.waiting.postMessage({type:'ACTIVATE_UPDATE'});};let replacing=false;navigator.serviceWorker?.addEventListener('controllerchange',()=>{if(replacing)location.reload();else replacing=true;});window.addEventListener('online',connection);window.addEventListener('offline',connection);
soundUI();home();save();verifyCache().then(()=>{if(screen==='home')home();});if(window.isSecureContext&&'serviceWorker'in navigator)navigator.serviceWorker.getRegistration().then(reg=>{if(reg){watchRegistration(reg);replacing=Boolean(reg.active);reg.update().catch(()=>{});}}).catch(()=>{});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_detective_progress',description:'Read local forest detective lesson progress without changing it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({chapter:chapterId,completed:progress().completed,total:lessons.length,chapters:Object.fromEntries(Object.entries(state.chapters).map(([id,p])=>[id,p.completed])),screen,offlineReady})})).catch(()=>{});}catch{}}
