'use strict';
let campOrder=[],campPicked=null,campSwaps=0,campChecked=false;
function resetCamp(l){campOrder=l?.type==='camp-place'?(l.initial?[...l.initial]:Array(l.slots.length).fill(null)):[];campPicked=null;campSwaps=0;campChecked=false;}
function campRuleOK(r,order,l){const index=order.indexOf(r.a);if(index<0)return false;const a=l.slots[index],other=order.indexOf(r.b),b=other<0?-1:l.slots[other],ax=a%l.cols,ay=Math.floor(a/l.cols),bx=b%l.cols,by=Math.floor(b/l.cols);
 if(r.kind==='at')return a===r.b;if(r.kind==='row')return ay===r.b;if(r.kind==='col')return ax===r.b;if(b<0)return false;
 if(r.kind==='right')return ay===by&&ax===bx+1;if(r.kind==='below')return ax===bx&&ay===by+1;
 const distance=Math.abs(ax-bx)+Math.abs(ay-by);return r.kind==='next'?distance===1:r.kind==='notnext'?distance>1:false;
}
function evaluateCamp(l,order,swaps=0){if(order.length!==l.friends.length||new Set(order).size!==l.friends.length||l.friends.some(id=>!order.includes(id)))return{ok:false,message:'先让每位朋友都找到一块草地，再检查线索。'};
 const failed=l.rules.find(r=>!campRuleOK(r,order,l));if(failed)return{ok:false,message:'再检查这条线索：'+failed.text+'。看看哪些位置需要调整。'};
 if(l.repair&&(swaps!==1||order.filter((id,i)=>id!==l.initial[i]).length!==2))return{ok:false,message:'这一关只交换一次。重新开始后，先想好要交换哪两位。'};
 return{ok:true};}
function campPortrait(id){return `<img class="camp-portrait" src="./assets/${id}.png" alt="${PICNIC_NAMES[id]}">`;}
function campMiniMap(r,l){return `<span class="camp-mini-map" style="--camp-cols:${l.cols}" aria-hidden="true">${Array.from({length:l.cols*2},(_,pos)=>`<i class="${!l.slots.includes(pos)?'water':(r.kind==='at'?pos===r.b:r.kind==='row'?Math.floor(pos/l.cols)===r.b:pos%l.cols===r.b)?'marked':''}"></i>`).join('')}</span>`;}
function campRulePicture(r,l){
 if(r.kind==='right')return `${campPortrait(r.b)}<span>→</span>${campPortrait(r.a)}`;
 if(r.kind==='below')return `<div class="camp-rule-below">${campPortrait(r.b)}<span>↓</span>${campPortrait(r.a)}</div>`;
 return `${campPortrait(r.a)}<span>${{at:'｜',row:'｜',col:'｜',next:'↔',notnext:'⋯'}[r.kind]}</span>${typeof r.b==='number'?campMiniMap(r,l):campPortrait(r.b)}`;
}
function campRules(l){return `<div class="camp-rules">${l.rules.map((r,i)=>`<div class="camp-rule ${campChecked&&!campRuleOK(r,campOrder,l)?'conflict':''}"><div class="camp-rule-picture" aria-hidden="true">${campRulePicture(r,l)}</div><small>${i+1}. ${r.text}${campChecked&&!campRuleOK(r,campOrder,l)?' · 再看看':''}</small></div>`).join('')}</div>`;}
function campBoard(){const l=lessons[step];return `${campRules(l)}<p class="camp-note">地图上方是上排 · 左右或上下紧挨才是邻居，斜对角不算</p><div class="camp-map" style="--camp-cols:${l.cols}" aria-label="两排营地地图">${Array.from({length:l.cols*2},(_,pos)=>{const i=l.slots.indexOf(pos),id=campOrder[i];return i<0?'<div class="camp-water" aria-label="池塘，不能扎营"><svg viewBox="0 0 90 70" aria-hidden="true"><ellipse cx="45" cy="37" rx="38" ry="23" fill="#9bccd6"/><path d="M19 31q12 8 23 0m-4 19q15 8 30-2" fill="none" stroke="#6ba3b3" stroke-width="3"/></svg><small>池塘 · 不能扎营</small></div>':`<button data-camp-slot="${i}" class="camp-slot ${id&&id===campPicked?'selected':''}" aria-label="${Math.floor(pos/l.cols)===0?'上':'下'}排第${pos%l.cols+1}块草地：${id?PICNIC_NAMES[id]:'空位'}" ${solved?'disabled':''}><small>${Math.floor(pos/l.cols)===0?'上':'下'}排 · ${pos%l.cols+1}</small>${id?campPortrait(id):'<span class="camp-tent" aria-hidden="true">△</span>'}<strong>${id?PICNIC_NAMES[id]:'放这里'}</strong></button>`;}).join('')}</div>${l.repair?`<p class="camp-note">已交换 ${campSwaps} / 1 次 · 需要时可重新开始</p>`:`<div class="camp-waiting"><small>集合处</small><div>${l.friends.filter(id=>!campOrder.includes(id)).map(id=>`<button data-camp-person="${id}" class="camp-person ${campPicked===id?'selected':''}" aria-pressed="${campPicked===id}" ${solved?'disabled':''}>${campPortrait(id)}<span>${PICNIC_NAMES[id]}</span></button>`).join('')||'<span class="camp-note">朋友们都进营地啦</span>'}</div><button class="secondary" id="camp-return" ${solved||!campPicked||!campOrder.includes(campPicked)?'disabled':''}>放回集合处</button></div>`}<div class="camp-tools"><span role="status">${campPicked?'已选 '+PICNIC_NAMES[campPicked]+'，再点目标草地':'先点朋友，再点草地；已住的两位可交换'}</span><button class="secondary" id="camp-reset" ${solved?'disabled':''}>重新开始</button></div>`;}
function campChanged(){campChecked=false;$('#feedback').hidden=true;refreshBoard();}
function bindCampBoard(){const l=lessons[step];document.querySelectorAll('[data-camp-person]').forEach(b=>b.onclick=()=>{if(solved)return;campPicked=campPicked===b.dataset.campPerson?null:b.dataset.campPerson;refreshBoard();});document.querySelectorAll('[data-camp-slot]').forEach(b=>b.onclick=()=>{if(solved)return;const i=Number(b.dataset.campSlot),occupant=campOrder[i];if(!campPicked){campPicked=occupant;refreshBoard();return;}if(campPicked===occupant){campPicked=null;refreshBoard();return;}if(l.repair&&campSwaps>=1){toast('已经交换一次。可以检查，或重新开始。');return;}const from=campOrder.indexOf(campPicked);if(from>=0)campOrder[from]=occupant;campOrder[i]=campPicked;campPicked=null;if(l.repair)campSwaps++;campChanged();});if($('#camp-return'))$('#camp-return').onclick=()=>{if(solved)return;const i=campOrder.indexOf(campPicked);if(i>=0)campOrder[i]=null;campPicked=null;campChanged();};$('#camp-reset').onclick=()=>{if(solved)return;resetCamp(l);campChanged();};$('#check').disabled=!solved&&(campOrder.some(x=>!x)||(l.repair&&campSwaps!==1));}
function checkCamp(){campChecked=true;return evaluateCamp(lessons[step],campOrder,campSwaps);}
