'use strict';
let gardenPicks={};
function resetGarden(){gardenPicks={};}
function gardenFits(bug,home){return Boolean(bug&&home&&(!home.color||bug.color===home.color)&&(!home.pattern||bug.pattern===home.pattern));}
function evaluateGarden(l,picks){const picked=l.options[picks.first];if(!picked)return{ok:false,message:'先选一张图，再来检查。'};
 if(l.mode==='visitor')return{ok:gardenFits(picked,l.target),message:'先看屋顶颜色，再看门牌花纹。两样都要和客人相同。'};
 if(l.mode==='odd')return{ok:!gardenFits(picked,l.target),message:'这只蝴蝶符合两条规则。再找找哪一只的花纹不同。'};
 if(!gardenFits(l.input,picked))return{ok:false,message:l.mode==='pair'?'先检查第一只蝴蝶：屋顶颜色和门牌花纹都要相同。':l.wrong};
 if(l.mode==='pair')return{ok:gardenFits(l.second,l.finalOptions[picks.last]),message:'第一只安排对啦。再看看第二只的颜色和花纹。'};
 return{ok:true};
}
const GARDEN_COLORS={red:'#e68c87',blue:'#80b5d2',yellow:'#edc967'};
function gardenPattern(pattern){if(pattern==='dot')return '<g fill="#fff9e9" stroke="#645b63" stroke-width="1.2"><circle cx="23" cy="29" r="4"/><circle cx="22" cy="48" r="4"/><circle cx="57" cy="29" r="4"/><circle cx="58" cy="48" r="4"/></g>';if(pattern==='stripe')return '<g stroke="#645b63" stroke-width="4" stroke-linecap="round"><path d="m14 29 17 9m-17 7 17 9m18-16 17-9m-17 25 17-9"/></g>';return '';}
function gardenBug(bug){const size=bug.size==='small'?.78:bug.size==='large'?1.1:1;
 return `<svg class="garden-bug" viewBox="0 0 80 84" role="img" aria-label="${{red:'红色',blue:'蓝色',yellow:'黄色'}[bug.color]}${{dot:'圆点',stripe:'条纹',plain:'无花纹'}[bug.pattern]}蝴蝶${bug.size==='small'?'，较小':bug.size==='large'?'，较大':''}"><g transform="translate(40 42) scale(${size}) translate(-40 -42)"><g fill="${GARDEN_COLORS[bug.color]}" stroke="#74616b" stroke-width="2"><path d="M38 38C6-8-7 42 24 46 0 70 32 81 39 49Z"/><path d="M42 38C74-8 87 42 56 46 80 70 48 81 41 49Z"/></g>${gardenPattern(bug.pattern)}<path d="M37 26q-5-12-11-13m17 13q5-12 11-13" stroke="#74616b" stroke-width="2" fill="none"/><rect x="36" y="24" width="8" height="40" rx="4" fill="#74616b"/></g></svg>`;
}
function gardenHome(home){return `<svg class="garden-house" viewBox="0 0 100 108" role="img" aria-label="${home.color?{red:'红',blue:'蓝',yellow:'黄'}[home.color]+'屋顶':'颜色不限'}，${home.pattern?{dot:'圆点',stripe:'条纹',plain:'无花纹'}[home.pattern]+'门牌':'花纹不限'}"><rect x="15" y="38" width="70" height="58" rx="8" fill="#fff6dc" stroke="#a69572" stroke-width="2"/><path d="m6 40 44-31 44 31Z" fill="${GARDEN_COLORS[home.color]||'#d5d6bd'}" stroke="#918367" stroke-width="2"/><rect x="30" y="47" width="40" height="35" rx="6" fill="#eee6da" stroke="#bba88b" stroke-width="2"/>${home.pattern==='dot'?'<g fill="#fff9e9" stroke="#645b63" stroke-width="1.4"><circle cx="40" cy="58" r="4"/><circle cx="58" cy="59" r="4"/><circle cx="48" cy="72" r="4"/></g>':home.pattern==='stripe'?'<path d="m36 55 26 6m-26 4 26 6m-26 4 26 3" stroke="#645b63" stroke-width="4"/>':home.pattern==='plain'?'': '<text x="50" y="70" text-anchor="middle" font-size="12" fill="#807456">不限</text>'}<path d="M8 99h84" stroke="#9db182" stroke-width="5" stroke-linecap="round"/></svg>`;}
function gardenOptions(items,group,kind){return `<div class="garden-options" role="group" aria-label="${group==='last'?'第二只的花屋':'第一组图画选项'}">${items.map((item,i)=>`<button class="garden-option ${gardenPicks[group]===i?'selected':''}" data-garden-group="${group}" data-garden-choice="${i}" aria-pressed="${gardenPicks[group]===i}" ${solved?'disabled':''}>${kind==='bug'?gardenBug(item):gardenHome(item)}<small>${kind==='bug'?'选这只':'选这间'}</small></button>`).join('')}</div>`;}
function gardenBoard(){const l=lessons[step],visitors=['visitor','odd'].includes(l.mode);return `<div class="garden-scene"><span class="garden-flower" aria-hidden="true">✿</span><div><small>${visitors?'花屋的规则':l.mode==='pair'?'第一位朋友':'这位朋友'}</small>${visitors?gardenHome(l.target):gardenBug(l.input)}</div><span class="garden-flower" aria-hidden="true">✿</span></div><p class="garden-note">${l.mode==='odd'?'选出走错门的那只蝴蝶':l.mode==='visitor'?'任选一位符合两条规则的客人':l.mode==='pair'?'第一步：给这位朋友选花屋':'对照这一关的规则，选一间花屋'}</p>${gardenOptions(l.options,'first',visitors?'bug':'home')}${l.mode==='pair'?`<div class="garden-scene second"><span class="garden-flower" aria-hidden="true">✿</span><div><small>第二位朋友</small>${gardenBug(l.second)}</div><span class="garden-flower" aria-hidden="true">✿</span></div><p class="garden-note">第二步：再给这位朋友选花屋</p>${gardenOptions(l.finalOptions,'last','home')}`:''}`;}
function bindGardenBoard(){const l=lessons[step];document.querySelectorAll('[data-garden-choice]').forEach(b=>b.onclick=()=>{if(solved)return;gardenPicks[b.dataset.gardenGroup]=Number(b.dataset.gardenChoice);$('#feedback').hidden=true;refreshBoard();});$('#check').disabled=!solved&&(gardenPicks.first===undefined||(l.mode==='pair'&&gardenPicks.last===undefined));}
function checkGarden(){return evaluateGarden(lessons[step],gardenPicks);}
